package org.neighbor.api;

public enum ErrorCode {
    //todo dummy for test purposes
    UNKNOWN_ERROR, NOT_FOUND_ERROR, GENERAL_SERVER_ERROR
    , ORG_WITH_EXTID_NOT_FOUND,
    ORG_HAS_LINKED_ENTITIES,
    ACCOUNT_NUMBER_IS_NOT_UNIQUE,
    BAD_FORMED_CREDENTIALS, USER_NOT_REGISTERED, USER_BLOCKED, ACCOUNT_NUMBER_NOT_EXIST, ACCOUNT_IS_BLOCKED, USER_ACTIVE, REGISTRATION_REQUESTED, ORG_BLOCKED, USER_NOT_FOUND, TOKEN_NOT_FOUND, SECURITY_VIOLATION, ORG_WITH_EXTID_ALREADY_EXISTS

}
