-- Hibernate: create table neighbor_user (
-- id bigint generated by default as identity,
--  account_id bigint,
--  activation_status integer,
--  created_on timestamp,
--  login varchar(255),
--  pin_code varchar(255),
--  updated_on timestamp,
--  user_phone varchar(255),
--  user_urn varchar(255),
--  primary key (id))

insert INTO neighbor_user (ac) VALUES ()